<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.opencloudb.route.function.PartitionByHashModTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2017-02-20T02:40:30" hostname="DESKTOP-T7UG6RU" time="3.179">
  <properties/>
  <testcase name="test" classname="org.opencloudb.route.function.PartitionByHashModTest" time="3.179"/>
  <system-out><![CDATA[10:40:30.700   INFO [Test worker-SendThread(127.0.0.1:56922)] (ClientCnxn.java:975) -Opening socket connection to server 127.0.0.1/127.0.0.1:56922. Will not attempt to authenticate using SASL (unknown error)
10:40:31.707   WARN [Test worker-SendThread(127.0.0.1:56922)] (ClientCnxn.java:1102) -Session 0x15a59642a2e0000 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
10:40:33.128   INFO [Test worker-SendThread(127.0.0.1:56922)] (ClientCnxn.java:975) -Opening socket connection to server 127.0.0.1/127.0.0.1:56922. Will not attempt to authenticate using SASL (unknown error)
Shard Count is 64, time elapsed: 2997
Shard Count is 63, time elapsed: 3177
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
